development:
  session: _railscollab_session
  secret: RYNKIRTOKYLHOKZODBKQMASHWNKNVMFEQHUCYTGN
  attach_to_s3: false
  s3_access_key: ''
  s3_secret_key: ''
  s3_bucket_prefix: ''

testing:
  session: _railscollab_session
  secret: RYNKIRTOKYLHOKZODBKQMASHWNKNVMFEQHUCYTGN
  attach_to_s3: false
  s3_access_key: ''
  s3_secret_key: ''
  s3_bucket_prefix: ''

production:
  session: _railscollab_session
  secret: RYNKIRTOKYLHOKZODBKQMASHWNKNVMFEQHUCYTGN
  attach_to_s3: false
  s3_access_key: ''
  s3_secret_key: ''
  s3_bucket_prefix: ''
